name: test_task_one
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  ###
  flutter_bloc: ^8.1.5
  go_router: ^14.0.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf